// <auto-generated />
using System;
using ImmoScorer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImmoScorer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ImmoScorerDbContext))]
    partial class ImmoScorerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ImmoScorer.Domain.Entities.Listing", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<decimal>("Area").HasColumnType("TEXT");
                b.Property<string>("Description").HasColumnType("TEXT");
                b.Property<string>("EnergyRating").HasMaxLength(2).HasColumnType("TEXT");
                b.Property<string>("ExternalId").HasMaxLength(200).HasColumnType("TEXT");
                b.Property<int?>("Floor").HasColumnType("INTEGER");
                b.Property<string>("OriginalUrl").HasMaxLength(2000).HasColumnType("TEXT");
                b.Property<decimal>("PricePerM2").HasColumnType("TEXT");
                b.Property<decimal>("ReferencePricePerM2").HasColumnType("TEXT");
                b.Property<int?>("Rooms").HasColumnType("INTEGER");
                b.Property<DateTime>("ScrapedAt").HasColumnType("TEXT");
                b.Property<Guid>("SearchId").HasColumnType("TEXT");
                b.Property<string>("Source").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Title").HasMaxLength(500).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("SearchId", "Score_Value").HasDatabaseName("IX_Listings_SearchId_Score_Value");
                b.HasIndex("Source", "ExternalId").IsUnique().HasDatabaseName("IX_Listings_Source_ExternalId");
                b.ToTable("Listings");
                b.OwnsOne("ImmoScorer.Domain.ValueObjects.Address", "Address", b1 =>
                {
                    b1.Property<string>("City").HasMaxLength(200).HasColumnName("Address_City").HasColumnType("TEXT");
                    b1.Property<string>("Neighborhood").HasMaxLength(200).HasColumnName("Address_Neighborhood").HasColumnType("TEXT");
                    b1.Property<string>("PostalCode").HasMaxLength(10).HasColumnName("Address_PostalCode").HasColumnType("TEXT");
                    b1.WithOwner().HasForeignKey("ListingId");
                    b1.ToTable("Listings");
                });
                b.OwnsOne("ImmoScorer.Domain.ValueObjects.Price", "Price", b1 =>
                {
                    b1.Property<decimal>("Amount").HasColumnName("Price_Amount").HasColumnType("TEXT");
                    b1.Property<string>("Currency").HasMaxLength(3).HasColumnName("Price_Currency").HasColumnType("TEXT");
                    b1.WithOwner().HasForeignKey("ListingId");
                    b1.ToTable("Listings");
                });
                b.OwnsOne("ImmoScorer.Domain.ValueObjects.Score", "Score", b1 =>
                {
                    b1.Property<int>("Value").HasColumnName("Score_Value").HasColumnType("INTEGER");
                    b1.WithOwner().HasForeignKey("ListingId");
                    b1.ToTable("Listings");
                });
                b.OwnsOne("ImmoScorer.Domain.ValueObjects.ScoreBreakdown", "ScoreBreakdown", b1 =>
                {
                    b1.Property<int>("AreaScore").HasColumnName("ScoreBreakdown_AreaScore").HasColumnType("INTEGER");
                    b1.Property<int>("EnergyScore").HasColumnName("ScoreBreakdown_EnergyScore").HasColumnType("INTEGER");
                    b1.Property<int>("FloorScore").HasColumnName("ScoreBreakdown_FloorScore").HasColumnType("INTEGER");
                    b1.Property<int>("PriceGapScore").HasColumnName("ScoreBreakdown_PriceGapScore").HasColumnType("INTEGER");
                    b1.WithOwner().HasForeignKey("ListingId");
                    b1.ToTable("Listings");
                });
            });

            modelBuilder.Entity("ImmoScorer.Domain.Entities.Search", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Status").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("CreatedAt").HasDatabaseName("IX_Searches_CreatedAt");
                b.ToTable("Searches");
                b.OwnsOne("ImmoScorer.Domain.ValueObjects.SearchCriteria", "Criteria", b1 =>
                {
                    b1.Property<string>("City").HasMaxLength(200).HasColumnName("Criteria_City").HasColumnType("TEXT");
                    b1.Property<decimal?>("MaxArea").HasColumnName("Criteria_MaxArea").HasColumnType("TEXT");
                    b1.Property<int?>("MaxRooms").HasColumnName("Criteria_MaxRooms").HasColumnType("INTEGER");
                    b1.Property<decimal?>("MaxPrice").HasColumnName("Criteria_MaxPrice").HasColumnType("TEXT");
                    b1.Property<decimal?>("MinArea").HasColumnName("Criteria_MinArea").HasColumnType("TEXT");
                    b1.Property<int?>("MinRooms").HasColumnName("Criteria_MinRooms").HasColumnType("INTEGER");
                    b1.Property<decimal?>("MinPrice").HasColumnName("Criteria_MinPrice").HasColumnType("TEXT");
                    b1.Property<string>("PostalCode").HasMaxLength(10).HasColumnName("Criteria_PostalCode").HasColumnType("TEXT");
                    b1.Property<string>("PropertyType").HasColumnName("Criteria_PropertyType").HasColumnType("TEXT");
                    b1.WithOwner().HasForeignKey("SearchId");
                    b1.ToTable("Searches");
                });
            });
#pragma warning restore 612, 618
        }
    }
}
